name: Daily Training

on:
  schedule:
    # Run at 2 AM UTC (off-peak hours)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

env:
  PYTHON_VERSION: '3.12'

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for changelog

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch new Wikipedia pages
      run: |
        # Get 50 random page titles
        TITLES=$(for i in {1..50}; do
          curl -Ls "https://en.wikipedia.org/wiki/Special:Random" |
          grep -oP '(?<=<title>).*?(?= - Wikipedia</title>)'
        done | jq -R . | jq -s .)
        
        # Feed titles to fetch_wikipedia.py
        python scripts/fetch_wikipedia.py --titles $TITLES
        
    - name: Train model
      run: |
        python scripts/train_llm.py --model-path 'models\final\' \
          --vocab-size 5000 \
          --d-model 256 \
          --num-heads 4 \
          --num-layers 4 \
          --max-length 512 \
          --batch-size 4 \
          --learning-rate 1e-4 \
          --min-pages 1

    - name: Clean up and push changes
      run: |
        # Stage changelog and model files
        git add data/changelog.json
        git add models/
        
        # Create commit with training details
        git commit -m "Daily training: $(date +'%Y-%m-%d')
        
        - Trained on new pages (5 attempted from each category)
        - Updated changelog
        - Saved new model checkpoint"
        
        git push

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-checkpoint
        path: models/final/
        retention-days: 7  # Keep only the last week's checkpoints
